version: '3.8'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: onlineshop-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongodb_data:/data/db
    networks:
      - onlineshop-network

#  service-discovery:
#    build:
#      context: ./service-discovery
#      dockerfile: Dockerfile
#    container_name: onlineshop-service-discovery
#    ports:
#      - "8761:8761"
#    networks:
#      - onlineshop-network
#    depends_on:
#      - mongodb
#
#  api-gateway:
#    build:
#      context: ./api-gateway
#      dockerfile: Dockerfile
#    container_name: onlineshop-api-gateway
#    ports:
#      - "9000:9000"
#    networks:
#      - onlineshop-network
#    depends_on:
#      - mongodb
#      - service-discovery
#    restart: on-failure
#
#  product-service:
#    build:
#      context: ./product-service
#      dockerfile: Dockerfile
#    container_name: onlineshop-product-service
#    ports:
#      - "8080:8080"
#    networks:
#      - onlineshop-network
#    depends_on:
#      - mongodb
#      - service-discovery
#    restart: on-failure
#
#  user-service:
#    build:
#      context: ./user-service
#      dockerfile: Dockerfile
#    container_name: onlineshop-user-service
#    ports:
#      - "8083:8083"
#    networks:
#      - onlineshop-network
#    depends_on:
#      - mongodb
#      - service-discovery
#    restart: on-failure
#
#  auth-service:
#    build:
#      context: ./auth-service
#      dockerfile: Dockerfile
#    container_name: onlineshop-auth-service
#    ports:
#      - "8084:8084"
#    networks:
#      - onlineshop-network
#    depends_on:
#      - mongodb
#      - user-service
#      - service-discovery
#    restart: on-failure
#
#  payment-service:
#    build:
#      context: ./payment-service
#      dockerfile: Dockerfile
#    container_name: onlineshop-payment-service
#    ports:
#      - "8085:8085"
#    networks:
#      - onlineshop-network
#    depends_on:
#      - mongodb
#      - service-discovery
#    restart: on-failure

networks:
  onlineshop-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local