apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: service-discovery
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-discovery
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: service-discovery
    spec:
      containers:
        - image: madhuraonline/ead-service-discovery
          name: onlineshop-service-discovery
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
