name: Build and Push Docker Images
on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug - List directory contents
        run: |
          echo "Root directory:"
          ls -R

      - name: Build and push product-service
        uses: docker/build-push-action@v3
        with:
          context: ./product-service
          file: ./product-service/Dockerfile
          push: true
          tags: madhuraonline/ead-product-service:latest



      - name: Build and push auth-service
        uses: docker/build-push-action@v3
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: madhuraonline/ead-auth-service:latest

      - name: Build and push user-service
        uses: docker/build-push-action@v3
        with:
          context: ./user-service
          file: ./user-service/Dockerfile
          push: true
          tags: madhuraonline/ead-user-service:latest

      - name: Build and push api-gateway
        uses: docker/build-push-action@v3
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: madhuraonline/ead-api-gateway:latest

      - name: Build and push service-discovery
        uses: docker/build-push-action@v3
        with:
          context: ./service-discovery
          file: ./service-discovery/Dockerfile
          push: true
          tags: madhuraonline/ead-service-discovery:latest

      - name: Debug - Docker build logs
        if: failure()
        run: |
          for service in product-service order-service auth-service inventory-service user-service api-gateway service-discovery; do
            echo "Building $service"
            docker build ./$service -t $service-debug || true
          done